version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django-app
hooks:
  BeforeInstall:
    - location: unzip.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: migrate_database.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
